# Generated by Django 2.0.1 on 2018-01-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starnavi', '0002_auto_20180127_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comment',
        ),
    ]
