# Generated by Django 2.0.1 on 2018-01-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starnavi', '0003_remove_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
