# Generated by Django 2.0.1 on 2018-02-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starnavi', '0005_auto_20180203_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
