# Generated by Django 2.0.1 on 2018-02-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starnavi', '0010_auto_20180206_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='author_id',
        ),
    ]
